export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const START_LOADING = 'START_LOADING'
export const END_LOADING ='END_LOADING'
export const LOG_IN_USER ='LOG_IN_USER'
export const LOG_OUT_USER ='LOG_OUT_USER'
export const SET_LOGIN_MESSAGE ='SET_LOGIN_MESSAGE'