export * as  Navigation from './navbar/Navbar';
export * as  Home from './homeScreen/Home'
export * as Footer from './footer/Footer';
export * as About from './about/About'
export * as Contact from './contact/contact'
export * as Donate from './donate/Donate' 
export * as Violence from './violence/Violence';
export * as Education from './education/Education';
export * as Partnerships from './partnerships/Patnerships';